#!/bin/sh
# Blocks commits when npm scripts for linting and tests fail.

printError () {
    echo "\n$(tput setaf 1)Error: $1 \n$(tput sgr0)"
}

NPM_COMMAND=`which npm`

if [ -f "$NPM_COMMAND" ]; then
    $NPM_COMMAND run lint && $NPM_COMMAND run test
else
    echo Missing npm command: $NPM_COMMAND
    exit 1
fi