#!/bin/bash
# Adds the Jira ticket ID to the commit message.

COMMIT_FILE=$1
COMMIT_MSG=$(cat $1)
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
# only match feature/bugfix branches and capture the ticket number
JIRA_ID=$(echo "$CURRENT_BRANCH" | grep -Ei "(feature|bugfix)\/" | grep -Eio "[A-Z]{1,10}-[0-9]{1,10}")

if [ -n "$JIRA_ID" ]; then
    echo "[$JIRA_ID] $COMMIT_MSG" > $COMMIT_FILE
fi